package org.luizlopes.websocket.model;

public enum CommandType {

    AGUARDAR_INICIO_JOGO, ESCOLHER_PERSONAGEM, ESPERAR_VEZ, LANCAR_DADOS, MOVER_JOGADOR, FAZER_PALPITE, EXIBIR_CARTA, VER_CARTA, ESCOLHER_JOGADA, FAZER_ACUSACAO, FORA_DA_PARTIDA;

}
