package org.luizlopes.websocket.model;

public enum InfoType {

    PERSONAGENS_DISPONIVEIS, ANOTACOES, JOGADORES, JOGADOR_ATUAL, ULTIMO_JOGADOR, PALPITE_FEITO, GANHOU_PARTIDA, JOGADOR_FORA_DA_PARTIDA;

}
