package org.luizlopes.domain.jogador;

public enum JogadorStatus {

    INICIANDO, PRONTO, ESPERANDO, LANCANDO_DADOS, MOVENDO, FAZENDO_PALPITE, ESPERANDO_EXIBIR_CARTA, EXIBINDO_CARTA, VENDO_CARTA;

}
