package org.luizlopes.domain.jogador;

public enum JogadorStatus {

    INICIANDO, PRONTO, ESPERANDO, LANCANDO_DADOS, MOVENDO, FAZENDO_PALPITE, ESPERANDO_EXIBIR_CARTA, EXIBINDO_CARTA, VENDO_CARTA, FAZENDO_ACUSACAO, ESCOLHENDO_JOGADA, ESPERANDO_APURAR_ACUSACAO, GANHOU_PARTIDA, FORA_DA_PARTIDA, FIM_DE_JOGO;

}
